language: android
jdk: oraclejdk7

notifications:
  email:
    on_success: never
    on_failure: always

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.0.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
    - sys-img-x86-android-21

before_install:
  # Gradle 2.1
  - wget http://services.gradle.org/distributions/gradle-2.1-bin.zip
  - unzip gradle-2.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - export  KEYSTORE=$HOME/snowdream.keystore
  - export  KEYSTORE_PASSWORD=1234567
  - export  KEY_ALIAS=snowdream
  - export  KEY_PASSWORD=1234567

  # environment info
  # - gradle -v

before_script:
  # write gradle.properties
  - wget https://gist.githubusercontent.com/snowdream/8120098/raw/5d2f4abb15ef02c79cc3f747b0b0af59a84d3204/gradle.properties -O  $HOME/.gradle/gradle.properties
  - wget https://raw.githubusercontent.com/SnowdreamFramework/android-gradle-template/develop/snowdream.keystore -O  $HOME/snowdream.keystore
  - wget https://raw.githubusercontent.com/SnowdreamFramework/android-gradle-template/develop/secring.gpg -O  $HOME/secring.gpg


  # Create and start emulator
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  # - TERM=dumb gradle build connectedCheck --info
  - TERM=dumb gradle build --info

